-- do not edit; automatically generated by UU.AG
module ConcreteSyntax where

import CommonTypes
import Patterns
import Rules
import UU.Pretty
import UU.Scanner.Position(Pos)
import Expression
-- AG ----------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for AG.AG:

-}
data AG = AG (Elems)
-- Alt ---------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Alt.Alt:

-}
data Alt = Alt (Pos) (Constructor) (Fields)
-- Alts --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Alts.Cons:

-}
{-
   local variables for Alts.Nil:

-}
type Alts = [(Alt)]
-- Attrs -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Attrs.Attrs:

-}
data Attrs = Attrs (Pos) (AttrNames) (AttrNames) (AttrNames)
-- ConstructorSet ----------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for ConstructorSet.CAll:

-}
{-
   local variables for ConstructorSet.CDifference:

-}
{-
   local variables for ConstructorSet.CName:

-}
{-
   local variables for ConstructorSet.CUnion:

-}
data ConstructorSet = CAll 
                    | CDifference (ConstructorSet) (ConstructorSet)
                    | CName (Constructor)
                    | CUnion (ConstructorSet) (ConstructorSet)
-- Elem --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Elem.Attr:

-}
{-
   local variables for Elem.Data:

-}
{-
   local variables for Elem.Deriving:

-}
{-
   local variables for Elem.Sem:

-}
{-
   local variables for Elem.Set:

-}
{-
   local variables for Elem.Txt:

-}
{-
   local variables for Elem.Type:

-}
{-
   local variables for Elem.Wrapper:

-}
data Elem = Attr (Pos) (NontSet) (Attrs)
          | Data (Pos) (Nonterminal) (Attrs) (Alts) (Bool)
          | Deriving (Pos) (NontSet) ([Name])
          | Sem (Pos) (Nonterminal) (Attrs) (SemAlts)
          | Set (Pos) (Name) (NontSet)
          | Txt (Pos) (Name) ([String])
          | Type (Pos) (Nonterminal) (ComplexType)
          | Wrapper (Pos) (NontSet)
-- Elems -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Elems.Cons:

-}
{-
   local variables for Elems.Nil:

-}
type Elems = [(Elem)]
-- NontSet -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for NontSet.All:

-}
{-
   local variables for NontSet.Difference:

-}
{-
   local variables for NontSet.Intersect:

-}
{-
   local variables for NontSet.NamedSet:

-}
{-
   local variables for NontSet.Path:

-}
{-
   local variables for NontSet.Union:

-}
data NontSet = All 
             | Difference (NontSet) (NontSet)
             | Intersect (NontSet) (NontSet)
             | NamedSet (Nonterminal)
             | Path (Nonterminal) (Nonterminal)
             | Union (NontSet) (NontSet)
-- SemAlt ------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for SemAlt.SemAlt:

-}
data SemAlt = SemAlt (Pos) (ConstructorSet) (SemDefs)
-- SemAlts -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for SemAlts.Cons:

-}
{-
   local variables for SemAlts.Nil:

-}
type SemAlts = [(SemAlt)]


