-- do not edit; automatically generated by UU.AG
module Expression where

import UU.Scanner.Position(Pos)
-- Expression --------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Expression.Expression:

-}
data Expression = Expression (Pos) (String)


