-- do not edit; automatically generated by UU.AG
module Rules where

import CommonTypes
import Patterns
import UU.Scanner.Position(Pos)
import Expression
-- SemDef ------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for SemDef.Def:

-}
data SemDef = Def (Pattern) (Expression) (Bool)
-- SemDefs -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for SemDefs.Cons:

-}
{-
   local variables for SemDefs.Nil:

-}
type SemDefs = [(SemDef)]


