-- do not edit; automatically generated by UU.AG
module Code where

import UU.Pretty
-- DataAlt -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for DataAlt.DataAlt:

-}
{-
   local variables for DataAlt.Record:

-}
data DataAlt = DataAlt (String) ([String])
             | Record (String) ([(String,String)])
-- DataAlts ----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for DataAlts.Cons:

-}
{-
   local variables for DataAlts.Nil:

-}
type DataAlts = [(DataAlt)]
-- Decl --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Decl.Comment:

-}
{-
   local variables for Decl.Data:

-}
{-
   local variables for Decl.Decl:

-}
{-
   local variables for Decl.NewType:

-}
{-
   local variables for Decl.TSig:

-}
{-
   local variables for Decl.Type:

-}
data Decl = Comment (String)
          | Data (String) (DataAlts) ([String])
          | Decl (Lhs) (Expr)
          | NewType (String) (String) (Type)
          | TSig (String) (Type)
          | Type (String) (Type)
-- Decls -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Decls.Cons:

-}
{-
   local variables for Decls.Nil:

-}
type Decls = [(Decl)]
-- Expr --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Expr.App:

-}
{-
   local variables for Expr.Lambda:

-}
{-
   local variables for Expr.Let:

-}
{-
   local variables for Expr.PP:

-}
{-
   local variables for Expr.SimpleExpr:

-}
{-
   local variables for Expr.TupleExpr:

-}
data Expr = App (String) (Exprs)
          | Lambda ([String]) (Expr)
          | Let (Decls) (Expr)
          | PP (PP_Doc)
          | SimpleExpr (String)
          | TupleExpr (Exprs)
-- Exprs -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Exprs.Cons:

-}
{-
   local variables for Exprs.Nil:

-}
type Exprs = [(Expr)]
-- Lhs ---------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Lhs.Fun:

-}
{-
   local variables for Lhs.Pattern:

-}
{-
   local variables for Lhs.TupleLhs:

-}
data Lhs = Fun (String) (Exprs)
         | Pattern (PP_Doc)
         | TupleLhs ([String])
-- Program -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Program.Program:

-}
data Program = Program (Decls)
-- Type --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Type.Arr:

-}
{-
   local variables for Type.List:

-}
{-
   local variables for Type.SimpleType:

-}
{-
   local variables for Type.TupleType:

-}
data Type = Arr (Type) (Type)
          | List (Type)
          | SimpleType (String)
          | TupleType (Types)
-- Types -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Types.Cons:

-}
{-
   local variables for Types.Nil:

-}
type Types = [(Type)]


