-- do not edit; automatically generated by UU.AG
module ErrorMessages where

import UU.Pretty
import CommonTypes
import UU.Scanner.Position(Pos)
import DepTypes(Trace)
-- Error -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Error.CircGrammar:

-}
{-
   local variables for Error.CustomError:

-}
{-
   local variables for Error.CyclicSet:

-}
{-
   local variables for Error.DupAlt:

-}
{-
   local variables for Error.DupChild:

-}
{-
   local variables for Error.DupInhAttr:

-}
{-
   local variables for Error.DupRule:

-}
{-
   local variables for Error.DupSet:

-}
{-
   local variables for Error.DupSynAttr:

-}
{-
   local variables for Error.DupSynonym:

-}
{-
   local variables for Error.MissingRule:

-}
{-
   local variables for Error.SuperfluousRule:

-}
{-
   local variables for Error.UndefAlt:

-}
{-
   local variables for Error.UndefAttr:

-}
{-
   local variables for Error.UndefChild:

-}
{-
   local variables for Error.UndefLocal:

-}
{-
   local variables for Error.UndefNont:

-}
data Error = CircGrammar (Nonterminal) (Name) (Trace) (Name) (Trace)
           | CustomError (Bool) (Pos) (PP_Doc)
           | CyclicSet (Name)
           | DupAlt (Nonterminal) (Constructor) (Constructor)
           | DupChild (Nonterminal) (Constructor) (Name) (Name)
           | DupInhAttr (Nonterminal) (Name) (Name)
           | DupRule (Nonterminal) (Constructor) (Name) (Name) (Name)
           | DupSet (Nonterminal) (Nonterminal)
           | DupSynAttr (Nonterminal) (Name) (Name)
           | DupSynonym (Nonterminal) (Nonterminal)
           | MissingRule (Nonterminal) (Constructor) (Name) (Name)
           | SuperfluousRule (Nonterminal) (Constructor) (Name) (Name)
           | UndefAlt (Nonterminal) (Constructor)
           | UndefAttr (Nonterminal) (Constructor) (Name) (Name)
           | UndefChild (Nonterminal) (Constructor) (Name)
           | UndefLocal (Nonterminal) (Constructor) (Name)
           | UndefNont (Nonterminal)


