-- do not edit; automatically generated by UU.AG
module HsToken where

import CommonTypes
import UU.Scanner.Position(Pos)
-- HsToken -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for HsToken.AGField:

-}
{-
   local variables for HsToken.AGLocal:

-}
{-
   local variables for HsToken.CharToken:

-}
{-
   local variables for HsToken.Err:

-}
{-
   local variables for HsToken.HsToken:

-}
{-
   local variables for HsToken.StrToken:

-}
data HsToken = AGField (Name) (Name) (Pos)
             | AGLocal (Name) (Pos)
             | CharToken (String) (Pos)
             | Err (String) (Pos)
             | HsToken (String) (Pos)
             | StrToken (String) (Pos)
-- HsTokens ----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for HsTokens.Cons:

-}
{-
   local variables for HsTokens.Nil:

-}
type HsTokens = [(HsToken)]
-- HsTokensRoot ------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for HsTokensRoot.HsTokensRoot:

-}
data HsTokensRoot = HsTokensRoot (HsTokens)


