-- do not edit; automatically generated by UU.AG
module Patterns where

import UU.Scanner.Position(Pos)
import CommonTypes
-- Pattern -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Pattern.Alias:

-}
{-
   local variables for Pattern.Constr:

-}
{-
   local variables for Pattern.Product:

-}
{-
   local variables for Pattern.Underscore:

-}
data Pattern = Alias (Name) (Name) (Pattern)
             | Constr (Constructor) (Patterns)
             | Product (Pos) (Patterns)
             | Underscore (Pos)
-- Patterns ----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Patterns.Cons:

-}
{-
   local variables for Patterns.Nil:

-}
type Patterns = [(Pattern)]


